module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    // Ensure these match with .storybook/preview.js
    screens: {
      xs: '375px',
      sm: '600px',
      md: '900px',
      lg: '1200px',
      xl: '1536px',
    },
    fontFamily: {
      sans: ['Arial', 'sans-serif'],
      serif: ['Garamond', 'serif'],
      mono: [
        // 'Courier New',
        'Monaco',
        'Menlo',
        'SFMono-Regular',
        'Consolas',
        'Liberation Mono',
        'monospace',
        'ui-monospace',
      ],
    },

    extend: {
      colors: {
        blue: {
          500: '#1a73e8',
        },
        rookie: '#44af86',
        explorer: '#f164c0',
        traveler: '#f39152',
        trailblazer: '#000',
        adventurer: '#000',
        discoverer: '#000',
        daredevil: '#000',
      },
      spacing: {
        128: '32rem',
        144: '36rem',
        160: '40rem',
        176: '44rem',
        192: '48rem',
      },
      fontSize: {
        '6xl': '5.052rem',
      },
      backgroundImage: {
        safe00: 'url(/start-safe/wallpaper-00.jpg)',
        safe01: 'url(/start-safe/wallpaper-01.jpg)',
        safe02: 'url(/start-safe/wallpaper-02.jpg)',

        x00: 'url(/start-x/wallpaper-x00.jpg)',
        x01: 'url(/start-x/wallpaper-x01.jpg)',
        x02: 'url(/start-x/wallpaper-x02.jpg)',
        x03: 'url(/start-x/wallpaper-x03.jpg)',
        x04: 'url(/start-x/wallpaper-x04.jpg)',
        x05: 'url(/start-x/wallpaper-x05.jpg)',
        x06: 'url(/start-x/wallpaper-x06.jpg)',
        x07: 'url(/start-x/wallpaper-x07.jpg)',
        x08: 'url(/start-x/wallpaper-x08.jpg)',
        x09: 'url(/start-x/wallpaper-x09.jpg)',
        x09b: 'url(/start-x/wallpaper-x09b.jpg)',
        x10: 'url(/start-x/wallpaper-x10.jpg)',
        x10b: 'url(/start-x/wallpaper-x10b.jpg)',
        x11: 'url(/start-x/wallpaper-x11.jpg)',
        x12: 'url(/start-x/wallpaper-x12.jpg)',
        x13: 'url(/start-x/wallpaper-x13.jpg)',
        x14: 'url(/start-x/wallpaper-x14.jpg)',
        x15: 'url(/start-x/wallpaper-x15.jpg)',
        x16: 'url(/start-x/wallpaper-x16.jpg)',
        x17: 'url(/start-x/wallpaper-x17.jpg)',
        x18: 'url(/start-x/wallpaper-x18.jpg)',
        x19: 'url(/start-x/wallpaper-x19.jpg)',
        x20: 'url(/start-x/wallpaper-x20.jpg)',
        x21: 'url(/start-x/wallpaper-x21.jpg)',
        x22: 'url(/start-x/wallpaper-x22.jpg)',
        x23: 'url(/start-x/wallpaper-x23.jpg)',
        x24: 'url(/start-x/wallpaper-x24.jpg)',
        x25: 'url(/start-x/wallpaper-x25.jpg)',
        x26: 'url(/start-x/wallpaper-x26.jpg)',
        x27: 'url(/start-x/wallpaper-x27.jpg)',
        x28: 'url(/start-x/wallpaper-x28.jpg)',
        x29: 'url(/start-x/wallpaper-x29.jpg)',
        x30: 'url(/start-x/wallpaper-x30.jpg)',
        x31: 'url(/start-x/wallpaper-x31.jpg)',
        x32: 'url(/start-x/wallpaper-x32.jpg)',
        x33: 'url(/start-x/wallpaper-x33.jpg)',
        x34: 'url(/start-x/wallpaper-x34.jpg)',
        x35: 'url(/start-x/wallpaper-x35.jpg)',
        x36: 'url(/start-x/wallpaper-x36.jpg)',
        x37: 'url(/start-x/wallpaper-x37.jpg)',
        x38: 'url(/start-x/wallpaper-x38.jpg)',
        x39: 'url(/start-x/wallpaper-x39.jpg)',
        x40: 'url(/start-x/wallpaper-x40.jpg)',
        x41: 'url(/start-x/wallpaper-x41.jpg)',
        x42: 'url(/start-x/wallpaper-x42.jpg)',
        x43: 'url(/start-x/wallpaper-x43.jpg)',
        x44: 'url(/start-x/wallpaper-x44.jpg)',
        x45: 'url(/start-x/wallpaper-x45.jpg)',
        x46: 'url(/start-x/wallpaper-x46.jpg)',
        x47: 'url(/start-x/wallpaper-x47.jpg)',
        x48: 'url(/start-x/wallpaper-x48.jpg)',
        x49: 'url(/start-x/wallpaper-x49.jpg)',
        x50: 'url(/start-x/wallpaper-x50.jpg)',
        x51: 'url(/start-x/wallpaper-x51.jpg)',
        x52: 'url(/start-x/wallpaper-x52.jpg)',
        x53: 'url(/start-x/wallpaper-x53.jpg)',
        x54: 'url(/start-x/wallpaper-x54.jpg)',
        x55: 'url(/start-x/wallpaper-x55.jpg)',
        x56: 'url(/start-x/wallpaper-x56.jpg)',
        x56b: 'url(/start-x/wallpaper-x56b.jpg)',
        x57: 'url(/start-x/wallpaper-x57.jpg)',
        x58: 'url(/start-x/wallpaper-x58.jpg)',
        x59: 'url(/start-x/wallpaper-x59.jpg)',
        x60: 'url(/start-x/wallpaper-x60.jpg)',
        x61: 'url(/start-x/wallpaper-x61.jpg)',
        x62: 'url(/start-x/wallpaper-x62.jpg)',
        x63: 'url(/start-x/wallpaper-x63.jpg)',
        x64: 'url(/start-x/wallpaper-x64.jpg)',
        x65: 'url(/start-x/wallpaper-x65.jpg)',
        x66: 'url(/start-x/wallpaper-x66.jpg)',
        x67: 'url(/start-x/wallpaper-x67.jpg)',
        x68: 'url(/start-x/wallpaper-x68.jpg)',
        x69: 'url(/start-x/wallpaper-x69.jpg)',
        x70: 'url(/start-x/wallpaper-x70.jpg)',
        x71: 'url(/start-x/wallpaper-x71.jpg)',
        x72: 'url(/start-x/wallpaper-x72.jpg)',
        x73: 'url(/start-x/wallpaper-x73.jpg)',
        x74: 'url(/start-x/wallpaper-x74.jpg)',
        x75: 'url(/start-x/wallpaper-x75.jpg)',
        x76: 'url(/start-x/wallpaper-x76.jpg)',
        x77: 'url(/start-x/wallpaper-x77.jpg)',
        x78: 'url(/start-x/wallpaper-x78.jpg)',
        x79: 'url(/start-x/wallpaper-x79.jpg)',
        x80: 'url(/start-x/wallpaper-x80.jpg)',
        x81: 'url(/start-x/wallpaper-x81.jpg)',
        x82: 'url(/start-x/wallpaper-x82.jpg)',
        x83: 'url(/start-x/wallpaper-x83.jpg)',
        x84: 'url(/start-x/wallpaper-x84.jpg)',
        x85: 'url(/start-x/wallpaper-x85.jpg)',
        x86: 'url(/start-x/wallpaper-x86.jpg)',
        x87: 'url(/start-x/wallpaper-x87.jpg)',
        x88: 'url(/start-x/wallpaper-x88.jpg)',
        x89: 'url(/start-x/wallpaper-x89.jpg)',
        x90: 'url(/start-x/wallpaper-x90.jpg)',
        x91: 'url(/start-x/wallpaper-x91.jpg)',
        x92: 'url(/start-x/wallpaper-x92.jpg)',
        x93: 'url(/start-x/wallpaper-x93.jpg)',
        x94: 'url(/start-x/wallpaper-x94.jpg)',
        x95: 'url(/start-x/wallpaper-x95.jpg)',
        x96: 'url(/start-x/wallpaper-x96.jpg)',
        x96b: 'url(/start-x/wallpaper-x96b.jpg)',
        x97: 'url(/start-x/wallpaper-x97.jpg)',
        x98: 'url(/start-x/wallpaper-x98.jpg)',
        x99: 'url(/start-x/wallpaper-x99.jpg)',

        xCN: 'url(/start-x/wallpaper-xCN.jpg)',
        xCO: 'url(/start-x/wallpaper-xCO.jpg)',
        xES: 'url(/start-x/wallpaper-xES.jpg)',
        xLV: 'url(/start-x/wallpaper-xLV.jpg)',
        xMX: 'url(/start-x/wallpaper-xMX.jpg)',
        xFI: 'url(/start-x/wallpaper-xFI.jpg)',
        xZM: 'url(/start-x/wallpaper-xZM.jpg)',
        xLT: 'url(/start-x/wallpaper-xLT.jpg)',
        xSG: 'url(/start-x/wallpaper-xSG.jpg)',
        xGT: 'url(/start-x/wallpaper-xGT.jpg)',
        xUS: 'url(/start-x/wallpaper-xUS.jpg)',
        xUA: 'url(/start-x/wallpaper-xUA.jpg)',
      },
    },
  },
  plugins: [],
};
